
// Mock data extracted from components to simulate API responses

export const MOCK_USERS = [
  {
    id: '1',
    name: 'Ahmed Al Mansouri',
    email: 'ahmed@smartbook.ae',
    role: 'Admin',
    status: 'active',
    lastActive: '5 minutes ago',
    phone: '+971 50 123 4567',
    teams: ['Leadership', 'Finance'],
    joinedDate: '2024-01-15',
  },
  {
    id: '2',
    name: 'Sarah Johnson',
    email: 'sarah@smartbook.ae',
    role: 'Finance Manager',
    status: 'active',
    lastActive: '2 hours ago',
    phone: '+971 50 234 5678',
    teams: ['Finance', 'Accounting'],
    joinedDate: '2024-02-20',
  },
  {
    id: '3',
    name: 'Mohammed Hassan',
    email: 'mohammed@smartbook.ae',
    role: 'Sales Representative',
    status: 'active',
    lastActive: '1 day ago',
    phone: '+971 50 345 6789',
    teams: ['Sales'],
    joinedDate: '2024-03-10',
  },
  {
    id: '4',
    name: 'Fatima Ali',
    email: 'fatima@smartbook.ae',
    role: 'Accountant',
    status: 'active',
    lastActive: '3 hours ago',
    phone: '+971 50 456 7890',
    teams: ['Accounting'],
    joinedDate: '2024-04-05',
  },
  {
    id: '5',
    name: 'John Smith',
    email: 'john@smartbook.ae',
    role: 'Report Viewer',
    status: 'inactive',
    lastActive: '2 weeks ago',
    phone: '+971 50 567 8901',
    teams: [],
    joinedDate: '2024-05-12',
  },
  {
    id: '6',
    name: 'Layla Abdullah',
    email: 'layla@smartbook.ae',
    role: 'Sales Representative',
    status: 'pending',
    lastActive: 'Never',
    phone: '+971 50 678 9012',
    teams: ['Sales'],
    joinedDate: '2024-12-01',
  },
];

export const MOCK_BRANCHES = [
  { id: 'A01', name: 'AZ Care Salwa' },
  { id: 'A02', name: 'AZ Care Al Mirqab' },
  { id: 'A03', name: 'AZ Care Ibn AlNafees' },
  { id: 'A04', name: 'AZ Care Alshafi' },
  { id: 'A05', name: 'AZ CARE New Faleh' },
  { id: 'A06', name: 'AZ Care Duhail' },
  { id: 'A07', name: 'AZ Care 01 Mall' },
  { id: 'A08', name: 'AZ Care Murra' },
  { id: 'A09', name: 'AZ Care Umm Qarn' },
  { id: 'A10', name: 'AZ Care Sailiya' },
  { id: 'A11', name: 'AZ Care Quartier' },
  { id: 'A12', name: 'AZ Care Izghawa' },
  { id: 'A13', name: 'AZ Care Hamama' },
  { id: 'A14', name: 'AZ Care Badria' },
  { id: 'A15', name: 'AZ Care Zero Four' },
];
